---
# ------------------------------------------------
# Template test 
# Sample : ansible-playbook template_test.yml
# ------------------------------------------------
- hosts: testnode

  tasks:
    - name: How to check the status of nginx
      debug: 
        msg: "{{ lookup('template', '/lcia/ansible/test/msg.j2').split('\n') }}" 
