# --------------------------------------------
# Host file create test using by template
# ansible-playbook template_hosts.yml
# --------------------------------------------
---
- name: Create hosts file by template
  hosts: testnode
  become: yes

  vars:
    Node_Number: 8

  tasks:
  - template:
      src: hosts.j2
      dest: /lcia/ansible/test/template/hosts
