---
# ----------------------------------------------------
# Template file create test
# Syntax: ansible-playbook template_file1.yml
# ----------------------------------------------------
- name: Create yml by template
  hosts: testnode

  tasks:
  - template:
      src: which_lnx.j2
      dest: /lcia/ansible/test/template/which_lnx.yml

