# -----------------------------------------------------------------------------------------------------
# Program     : wex_template_test.yml
# Description : when after wex data reindexing job  
# Creator     : Lee Sang Hyoung
# Syntax      : ansible-playbook wex_template_test.yml -e '{"rlddate1":yyyymmdd,"rlddate2":yyyymmdd}'
# Syntax      : ansible-playbook wex_template_test.yml -e '{"rlddate1":20180909,"rlddate2":20180910}'
# -----------------------------------------------------------------------------------------------------
---
- hosts: localhost
  remote_user: admin
  vars: 
    - reloaddate1: "{{ rlddate1 }}"
    - reloaddate2: "{{ rlddate2 }}"
    - oozielist: 
      - {jobname: WFO_0015_ANA_DD, jobid: hue-oozie-1511774951.05} 
      - {jobname: WFO_RE01_ANA_DD, jobid: hue-oozie-1512279629.53}

  tasks:
    #- name: Running Job 1 
    #  include_tasks: wex_reload_ided1.yml
    #  vars: 
    #    - jobname: "{{ item.jobname }}" 
    #    - jobid: "{{ item.jobid }}"
    #    - reloaddate2: "{{ rlddate2 }}"
    #  with_items: 
    #    - "{{ oozielist1 }}" 

    - template: 
        src: /home/admin/ansible/test/template/wfo_template.j2
        dest: /home/admin/ansible/test/template/{{ jobname }}/job.properties
      vars:
        - jobname: "{{ item.jobname }}"
        - jobid: "{{ item.jobid }}"
      with_items:
        - "{{ oozielist }}"

    #- name: Running Job 2 
    #  include_tasks: wex_reload_ided2.yml
    #  vars: 
    #    - jobname: "{{ item.jobname }}" 
    #    - jobid: "{{ item.jobid }}"
    #    - reloaddate1: "{{ rlddate1 }}"
    #    - reloaddate2: "{{ rlddate2 }}"
    #  with_items: 
    #    - "{{ oozielist2 }}" 


