# ---------------------------------------------------
# Template create sample
# Create by Template at 2018-01-08
# ---------------------------------------------------
---
- name: Install nginx on the nodes
  hosts: nodes
  become: yes
  vars: |-
    lnx_name: "{{'Ubuntu' if ansible_distribution == 'Ubuntu' 
                              else 'CentOS' if ansible_distribution == 'CentOS' 
                              else 'RedHat' if ansible_distribution == 'RedHat' 
                              else 'Just Linux' }}"

  tasks:
  - name: nginx for Any Linux
    include_tasks: "{{ lnx_name }}.yml"
