#####################################################################################################
# Program : adduser_work.yml
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook adduser_work.yml -t SSHKEY -e "host=wexnode user=admin" --ask-pass
# Syntax : ansible-playbook adduser_work.yml -t CREATUSER -e "host=wexnode user=esadmin" --ask-pass
# Syntax : ansible-playbook adduser_work.yml -t REMOVEUSER -e "host=wexnode user=esadm" --ask-pass
# Syntax : ansible-playbook adduser_work.yml -t CREATUSER -e "host=lcia-dnaedge01,lcia-dnaedge02,lcia-spss02 user=user01" --ask-pass
#####################################################################################################
--- 
- hosts: "{{ host }}"
  user: root
  vars:
    - host: "{{ host }}"
    - user: "{{ user }}"

  tasks:
    - name: Remove user --> "{{ user }}"
      user:
        name: "{{ user }}"
        state: absent
        remove: yes 
      tags:
        - REMOVEUSER

    - name: Create user --> "{{ user }}"
      user:
        name: "{{ user }}"
        password: "{{ 'user01!@#' | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create
      tags: 
        - CREATUSER

    - name: Ensure user information 
      user: 
        name="{{ user }}" 
        comment="Created by Ansible" 
        group="{{ user }}"
      tags:
        - CREATUSER

    - name: Ensure directory exists
      file:
        path: /home/"{{ user }}"/.ssh
        state: directory
        group: "{{ user }}"
        owner: "{{ user }}"
        mode: 0755
      tags:
        - SSHKEY

    - name: Ensure file exists
      copy:
        content: ""
        dest: /home/"{{ user }}"/.ssh/authorized_keys
        force: no
        group: "{{ user }}"
        owner: "{{ user }}"
        mode: 0755
      tags:
        - SSHKEY

    - name: Upload SSH key 
      authorized_key: 
        user: "{{ user }}" 
        state: present
        key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_dsa.pub') }}"
      tags:
        - SSHKEY

