# -----------------------------------------------------------------------------------------
# Program : command_work.yml
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook command_work.yml -t AMBARI-AGENT -e "host=edgenode module=status"
# -----------------------------------------------------------------------------------------
---
- hosts: "{{ host }}"
  remote_user: admin
  become: yes

  tasks:
    - name: "{{ module }} Service Start "
      shell: 'nohup {{ module }} -s &'
      with_items:
        - host: "{{ host }}"
        - module: "{{ module }}"
      tags:
        - COMMON

    - name: Ambari-agent
      shell: ambari-agent {{ module }}
      register: job_result
      tags:
        - AMBARI-AGENT 

    - name: Ambari-agent result
      debug:
        msg: "{{ job_result.stdout_lines }}"
      tags:
        - AMBARI-AGENT 
   
