---
- hosts: lcia-dnaland01 
  remote_user: admin

  tasks:
    - name: Work 2. file Copy to landing zone
      copy:
        #src: /lcia/data/*.csv
        src: "{{ item }}"
        dest: /lcia/src/DW/
      with_fileglob:
        - /lcia/data/*.csv
  
  #tasks:
  #  - name: Work 2. file Copy to landing zone
  #    #command: scp /lcia/data/test.csv admin@10.109.2.71:/lcia/src/DW/
  #    copy: 
  #      src: /lcia/data/test.csv 
  #      dest: /lcia/src/DW/
