---
- hosts: localhost
  remote_user: admin

  tasks:
    - name: Test Message Debug 
      #shell: ls -l /lcia/ansible 
      command: ansible --version
      register: ansibleresult

    - name: Print Job Result
      debug: 
        msg: "Job Result: {{ ansibleresult.stdout }}"
