---
- hosts: localhost
  remote_user: admin
  
  tasks:
  - name: Rm file wildcard
    find:
      paths: /lcia/data
      patterns: "*.csv"
    register: find_results

  - name: Work rm. File delete after scp
    file:
      path: "{{ item['path'] }}" 
      state: absent
    with_items: "{{ find_results['files'] }}"
