#####################################################################################
# Program : diskspace_check_work.yml
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook diskspace_check_work.yml 
#####################################################################################
---
- hosts: localhost
  become: true
# remote_user: admin
# become_user: esadmin
# become_method: sudo

  tasks:
    ######################################
    # 남은 용량이 35% 이하일 경우 체크 
    # 필요한 경우 작업 호출 또는 수행 
    ######################################
    - name: test for available disk space
      assert:
        that: 
          - item.mount == '/lcia' and ( item.size_available < item.size_total - ( item.size_total|float * 0.65 ) ) 
      with_items: "{{ ansible_mounts }}"
      ignore_errors: yes
      register: disk_free
      when: "item.mount == '/lcia'"

    - name: free disk space
      command: "/some/command/that/fixes/it"
      when: disk_free | failed
    
    - debug:
        msg:
          - "상태 : {{ disk_free }}"

