# ----------------------------------------------------------------------------------------------------------------------------
# Program : dna_reload_works.yml
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook dna_reload_works.yml -e "jobname='kosk003' jobid='hue-oozie-1516786023.33' reloaddate='20180126'" 
# ----------------------------------------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge02
  remote_user: admin
  become: yes
  become_user: lcia-dna
  become_method: sudo

  vars: 
    - jobname: "{{ jobname }}"
    - jobid: "{{ jobid }}"
    - reloaddate: "{{ reloaddate }}"

  tasks:
    - name: Change STDR_DATE
      lineinfile:
        path: /home/lcia-dna/oozie-cli/{{ jobname }}/job.properties
        regexp: '^STDR_DATE'
        line: STDR_DATE={{ reloaddate }}

    - name: Oozie data reload job 
      command: >
        oozie job --oozie
        http://10.109.2.73:11000/oozie
        -config /home/lcia-dna/oozie-cli/'{{ jobname }}'/job.properties
        -run
      register: ooziejobcall

    - name: Print Job Result 1
      debug:
        msg: "Job Result: {{ ooziejobcall }}"

    - name: Oozie job status check
      command: >
        oozie jobs --oozie  http://10.109.2.73:11000/oozie
        '{{ jobid }}' -filter status=RUNNING  |
        grep "No Jobs match" |
        awk '{print $1 $2 $3}'
      register: ooziejobstatus
      until: ooziejobstatus.stdout.find("No Jobs match") != -1
      retries: 300
      delay: 10

    - name: Print Job Result 2
      debug:
        msg: "Job Result: {{ ooziejobstatus.stdout }} Next Job Process .... "

