##################################################################################################
# Program : dna_reload_ider.yml
# Creator : Lee Sang Hyoung
# Syntax1 : ansible-playbook dna_reload_ider.yml --extra-vars '{"rlddate":[yyyymmdd]}'
# Syntax2 : ansible-playbook dna_reload_ider.yml --extra-vars '{"rlddate":[yyyymmdd,yyyymmdd]}'
##################################################################################################
---
- hosts: lcia-dnaedge02
  remote_user: admin
  become: yes
  become_user: lcia-dna
  become_method: sudo
  vars: 
    ###############################################################
    # DW 마스터 데이터 적재 
    ###############################################################
    oozielist1: 
      - {jobname: WFO_0008_SOR_DD, jobid: hue-oozie-1511843089.3}

    ###############################################################
    # SAP마스터, SAP매출, 엘포인트POS/SEG, 닐슨POS  
    ###############################################################
    oozielist2: 
      - {jobname: WFO_0003_SOR_DD, jobid: hue-oozie-1508912001.31}
      - {jobname: WFO_0007_SOR_DD, jobid: hue-oozie-1509346605.2}
      - {jobname: WFO_0002_SOR_DD, jobid: hue-oozie-1512352572.08}
      - {jobname: WFO_0009_SOR_DD, jobid: hue-oozie-1511919447.57}
      - {jobname: WFO_0013_SOR_DD, jobid: hue-oozie-1513325505.59}
      #-----------------------------------------------------------
      #- {jobname: WFO_0012_SOR_DD, jobid: hue-oozie-1513322263.39}
      #- {jobname: kosk003, jobid: hue-oozie-1516786023.33}

    ###############################################################
    # DW정형, RSN, 비정형보고서, WEX, 날씨, 인구
    ###############################################################
    oozielist3: 
      - {jobname: WFO_0011_SOR_DD, jobid: hue-oozie-1513131212.09}
      - {jobname: WFO_0001_SOR_HH, jobid: hue-oozie-1504686177.49}
      - {jobname: WFO_0005_SOR_DD, jobid: hue-oozie-1508843527.11}
      - {jobname: WFO_0010_SOR_DD, jobid: hue-oozie-1512116282.15}
      - {jobname: WFO_0006_SOR_DD, jobid: hue-oozie-1509002847.61}
      - {jobname: WFO_0004_SOR_MM, jobid: hue-oozie-1505093471.37}
      #-----------------------------------------------------------
      #- {jobname: WFO_0015_ANA_DD, jobid: hue-oozie-1511774951.05} 
      #- {jobname: WFO_P001_SOR_DD, jobid: hue-oozie-1516785538.56} 

    ###############################################################
    # 닐슨/엘포인트 판매집계
    ###############################################################
    oozielist4: 
      - {jobname: WFO_0018_ANA_WW, jobid: hue-oozie-1516784734.5}

    ###############################################################
    # 삭제예정
    ###############################################################
    #oozielist5: 
    #  - {jobname: WFO_9993_SOR_DD, jobid: hue-oozie-1515660235.62} 

  tasks:
    ################################################
    # DW 마스터 데이터 적재 
    ################################################
    - name: Running Job 1 
      include_tasks: dna_reload_ided.yml
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
        - reloaddate: "{{ rlddate | max() }}"
      with_items: 
        - "{{ oozielist1 }}" 

    ################################################
    # SAP마스터, SAP매출, 엘포인트POS/SEG, 닐슨POS  
    ################################################
    - name: Running Job 2 
      include_tasks: dna_reload_ided.yml
      vars: 
        - jobname: "{{ item[1].jobname }}" 
        - jobid: "{{ item[1].jobid }}"
        - reloaddate: "{{  lookup('pipe', modedate1 + modedate2 + modedate3 ) }}"
        - modedate1: "date +%Y%m%d -d '"
        - modedate2: "{{ item[0] }}"
        - modedate3: " -1 day'"
      with_nested: 
        - "{{ rlddate }}"
        - "{{ oozielist2 }}"

    ################################################
    # DW정형, RSN, 비정형보고서, WEX, 날씨, 인구
    ################################################
    - name: Running Job 3 
      include_tasks: dna_reload_ided.yml
      vars: 
        - jobname: "{{ item[1].jobname }}" 
        - jobid: "{{ item[1].jobid }}"
        - reloaddate: "{{ item[0] }}"
      with_nested:
        - "{{ rlddate }}"
        - "{{ oozielist3 }}"

    ################################################
    # 닐슨/엘포인트 판매집계
    ################################################
    - name: Running Job 4 
      include_tasks: dna_reload_ided.yml
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
        - reloaddate: "{{ rlddate | max() }}"
      with_items: 
        - "{{ oozielist4 }}" 

    ################################################
    # 삭제예정
    ################################################
    #- name: Running Job 5 
    #  include_tasks: dna_reload_ided.yml
    #  vars: 
    #    - jobname: "{{ item[1].jobname }}" 
    #    - jobid: "{{ item[1].jobid }}"
    #    - reloaddate: "{{ item[0] }}"
    #  with_nested:
    #    - "{{ rlddate }}"
    #    - "{{ oozielist5 }}"

