# -------------------------------------------------------------------------------------------
# Program : expgbk_work.yml
# Purpose : System backup file save to HDFS 
#           backupfile(each server) --> landing zone --> cp to HDFS & 10 day passed file rm 
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook expgbk_work.yml -e "host=lcia-dev01"
# -------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge01
  remote_user: admin
  vars:
    with_items:
      - host: "{{ host }}"

  tasks:
    - name: "Copy file from {{ host }} to landing zone"
      synchronize:
        src: /lcia/ansible/test
        dest: /home/admin/PGBACKUP
      delegate_to: "{{ host }}" 
 
    - name: Copy file to HDFS 
      command: /usr/bin/hdfs dfs -copyFromLocal -f /home/admin/PGBACKUP/msg_test.log /pgbackup 

    - name: Delete file over 10 day
      shell: > 
        hdfs dfs -ls /pgbackup | tr -s " " | cut -d' ' -f6-8 | grep "^[0-9]" | 
        awk 'BEGIN{ MIN=14400; LAST=60*MIN; "date +%s" | getline NOW } 
        { cmd="date -d'\''"$1" "$2"'\'' +%s"; cmd | getline WHEN; DIFF=NOW-WHEN; 
        if(DIFF > LAST) { system("hdfs dfs -rm -r "$3) }}'

