#####################################################################################################
# Program : file_work.yml
# Description : 로컬(Ansible)에서 실행file 복사 --> 실행 --> 결과 저장 --> 로그파일 Local로 복사 
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook file_work.yml  
#          ansible-playbook file_work.yml -e "host=lcia-dnaland01,lcia-dnaedge01"
#####################################################################################################
--- 

- hosts: "{{ host }}"
  remote_user: admin
  become_user: root
  become: true
  become_method: sudo

  tasks:
    ############################################################
    # 1. 로컬의 파일을 원격서버로 복사 
    ############################################################
    - name: copying file with owner and permissions
      copy:
        src: /tmp/linux.sh
        dest: /tmp/etc/
        owner: admin
        group: admin
        mode: 0755

    ############################################################
    # 2. 원격서버에서 파일 실행 및 결과값 파일 생성
    ############################################################
    - name: "파일실행상태 확인"
      shell: sh /tmp/etc/linux.sh > /tmp/etc/{{ inventory_hostname }}.log
      register: statuscheck

    - name: "수행상태 Check"
      debug:
        msg: "{{ statuscheck.stdout }}"

    ############################################################
    # 3. 원격서버의 결과값 파일을 로컬(Ansible)로 복사
    ############################################################
    - name: "생성된 파일을 Local(Ansible이 실행되는)로 복사"
      fetch:
        src: /tmp/etc/{{ inventory_hostname }}.log
        dest: /tmp/syscheck_result/
        flat: yes

    ############################################################
    # 4. 원격서버의 로그파일 및 디렉토리 삭제
    ############################################################
    - name: "원격서버의 로그파일 및 디렉토리 삭제"
      file:
        path: /tmp/etc
        state: absent

#- hosts: "{{ host }}"
#  remote_user: admin
#  become_user: root
#  become: true
#  become_method: sudo

#  vars:
#    - host: "{{ host }}"
#    - user: "{{ user }}"

#  tasks:
#    - name: RSA Key 생성
#      user: 
#        name: "{{ user }}"
#        generate_ssh_key: yes

#    - name: RSA Key를 임시폴더(Ansible이 실행되는 Local서버)로 복사 
#      fetch: 
#        src: /home/{{ user }}/.ssh/id_rsa.pub 
#        dest: /tmp/id_rsa.tmp 
#        flat: yes

#    - name: Ansible서버 임시폴더의 RSA Key를 Remote서버로 복사 
#      local_action: shell cat /tmp/id_rsa.tmp | ssh -p 22 {{ user }}@10.109.2.89 "cat >> /{{ user }}/.ssh/authorized_keys"

#    - name: 임시 폴더내용 삭제 
#      local_action: file  path=/tmp/id_rsa.tmp state=absent

#- hosts: lcia-minsky01
#  remote_user: admin
#  become_user: "{{ user }}"
#  become: true
#  become_method: sudo

#  tasks:
#    - name: "폴더의 권한 조정"
#      shell: | 
#        sh chmod go-w /home/admin/
#        sh chmod 700 /home/admin/.ssh
#        sh chmod 600 /home/admin/.ssh/authorized_keys

