###################################################################################################
# Program     : fsmount_work.yml
# Description : create directory and mount disk 
# Creator     : Lee Sang Hyoung
# Syntax      : 
#   Mount     : ansible-playbook fsmount_work.yml -t FSMOUNT -e "host=lcia-spss02" 
#   Unmount   : ansible-playbook fsmount_work.yml -t FSUNMOUNT -e "host=lcia-spss02" 
#   Directory : ansible-playbook fsmount_work.yml -t MKDIR -e "host=wexnode fsuser=root"
###################################################################################################
--- 
- hosts: "{{ host }}"
  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo

  vars:
    - host: "{{ host }}"
    - fsuser: "{{ fsuser }}"

  tasks:
    - name: Create directory for mount
      file:
        path: /home/onm
        state: directory
        owner: "{{ fsuser }}"
        group: "{{ fsuser }}"
        #owner: esadmin
        #group: esadmin
        mode: 0755
      register: mkdir_result
      tags:
        - MKDIR
    - debug:   
        msg: "Mkdir work result .. {{ mkdir_result.stdout }}"

    - name: Add mount disk 
      filesystem:
        fstype: ext4
        dev: /dev/vdd
      tags:
        - FSMOUNT

    - name: Add mount disk 
      mount:
        path: /lcia/data2
        src: /dev/vdd
        fstype: ext4
        opts: defaults
        state: mounted
      register: mountinfo_result
      tags:
        - FSMOUNT

    - name: Unmount disk 
      mount:
        path: /lcia/bak
        src: /dev/vdc
        fstype: ext4
        state: absent
      register: mountinfo_result
      tags:
        - FSUNMOUNT

    - debug:   
        msg: "Mount information add work result .. {{ mountinfo_result.stdout }}"

######################################

#    - name: Add mount disk
#      mount:
#        src: 10.109.2.90:/data
#        fstype: nfs
#        opts: defaults,_netdev
#        state: mounted
#      register: mountinfo_result
#      tags:
#        - FSMOUNT

#    - name: Unmount disk
#      mount:
#        path: /lcia
#        src: 10.109.2.90:/data
#        fstype: nfs
#        state: absent
#      register: mountinfo_result
#      tags:
#        - FSUNMOUNT

