# -------------------------------------------------------------------------------------------
# Program : lineinfile.yml
# Purpose : file contents change test 
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook lineinfile.yml 
# -------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge02 
  remote_user: admin
# become: true
# become_user: lcia-dna
# become_method: sudo

  tasks:
    - name: lineinfile job 
      lineinfile:
        path: /home/admin/work/{{ item.job }}
        regexp: (?<=INSERT OVERWRITE TABLE )(.*)(?={{ item.table }} PARTITION)
        line: LCIA
      register: jobresult
      with_items:
        - { job: test.hql, table: ANA_SAL10010_M }
#        - { job: ANA_SAL10010_M.hql, table: ANA_SAL10010_M }
#        - { job: ANA_SAL10011_M.hql, table: ANA_SAL10011_M }
#        - { job: ANA_SAL10040_M.hql, table: ANA_SAL10040_M }
#        - { job: ANA_SAL10041_M.hql, table: ANA_SAL10041_M }
#        - { job: ANA_SAL10042_M.hql, table: ANA_SAL10042_M }
#        - { job: ANA_SAL10030_M.hql, table: ANA_SAL10030_M }
#        - { job: ANA_SAL10031_M.hql, table: ANA_SAL10031_M }
#        - { job: ANA_SAL10032_M.hql, table: ANA_SAL10032_M }
#        - { job: ANA_SAL10033_M.hql, table: ANA_SAL10033_M }
#        - { job: ANA_SAL10034_M.hql, table: ANA_SAL10034_M }

    - name: Print Job Result
      debug:
        msg: "Job Result: {{ jobresult }}"
  



