# ---------------------------------------------------
# ansible-playbook loop_test2.yml -t NETSTED4
# ---------------------------------------------------
---
- hosts: localhost
  vars:
    nested_list3:
      - { val1: oneone, val2: 11}
      - { val1: twotwo, val2: 22}
      - { val1: thrthr, val2: 33}
  tasks:
    - name: "nested list 1"
      debug:
        msg: "{{ item }}"
      vars:
        nested_list:
          - - one
            - two
            - three
      with_items: "{{ nested_list }}"
      tags: NETSTED1

    - name: "nested list 2"
      debug:
        msg: "{{ item }}"
      vars:
        nested_list:
          - - one
            - two
            - three
      with_items: 
        - "{{ nested_list }}"
      tags: NETSTED2

    - name: "nested list 3"
      debug:
        msg: "{{ item.val1 }} | {{ item.val2 }}"
      with_items: "{{ nested_list3 }}"
      register: output
      tags: NETSTED3

    - name: "Nested Loop test"
      debug: 
        msg: "{{ jobname }} | {{ jobid }} "
      with_netsed: 
        - ['20180126','20180127']
        - [jobname: kosk003, jobid: hue-oozie-1516786023.33]
      tags: NETSTED4

