# -----------------------------------------------------------------------------------------
# Program : loop_test.yml
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook loop_test.yml -e "host=testnode"
# -----------------------------------------------------------------------------------------
---

- hosts: "{{ host }}"
  remote_user: admin
  become: yes
  vars:
    with_items:
      - host: "{{ host }}"

  tasks:
    - name: "Test with_items position"
      debug:
        msg: "Test .... "

