# -----------------------------------------------------------------------------------------
# Program : ntp_work.yml
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook ntp_work.yml -e "host=nutanixnode" 
# -----------------------------------------------------------------------------------------
---
- hosts: "{{ host }}" 
  remote_user: admin
  become: yes
  become_method: sudo 
  vars:
    with_items:
      - host: "{{ host }}"

  tasks:
    - name: set timezone
      shell: timedatectl set-timezone Asia/Seoul 

    - name: Install NTP
      yum: name=ntp state=installed 

    - name: Copy over the NTP configuration
      template: src=/lcia/ansible/template/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntpd

    - name: Make sure NTP is stopped
      service: name=ntpd state=stopped enabled=yes

    - name: Sync time initialy
      shell: ntpdate 10.238.65.86

    - name: Make sure NTP is started up
      service: name=ntpd state=started enabled=yes

    #- name: Sync hwclock
    #  shell: hwclock -w

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

