# -------------------------------------------------------------------------------------------
# Program : oozie_cli_prepare2.yml
# Purpose : oozie cli basic configuration setting  
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook oozie_cli_prepare2.yml -t MKDIR, CPLOCAL, MODPROPERTI
# -------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge02
  remote_user: admin
  become: yes
  become_user: lcia-dna
  become_method: sudo
  vars:
    oozielist:
      - { clidir: WFO_0008_SOR_DD, hdfsdir: hue-oozie-1511843089.3  }
      - { clidir: WFO_0003_SOR_DD, hdfsdir: hue-oozie-1508912001.31 }
      - { clidir: WFO_0007_SOR_DD, hdfsdir: hue-oozie-1509346605.2  }
      - { clidir: WFO_0002_SOR_DD, hdfsdir: hue-oozie-1512352572.08 }
      - { clidir: WFO_0009_SOR_DD, hdfsdir: hue-oozie-1511919447.57 }
      - { clidir: WFO_0011_SOR_DD, hdfsdir: hue-oozie-1513131212.09 }
      - { clidir: WFO_0012_SOR_DD, hdfsdir: hue-oozie-1513322263.39 }
      - { clidir: WFO_0013_SOR_DD, hdfsdir: hue-oozie-1513325505.59 }

  tasks:
    - name: "create directory for each oozie job cli"
      file:
        path: /home/lcia-dna/oozie-cli/{{ item.clidir }}
        state: directory 
        owner: lcia-dna
        group: hadoop
        mode: 0755
      with_items: 
        - "{{ oozielist }}"
      tags:
        - MKDIR

    - name: Copy file from HDFS to local 
      shell: >
        /usr/bin/hdfs dfs -copyToLocal 
        /user/hue/oozie/workspaces/{{ item.hdfsdir }}/job.properties 
        /home/lcia-dna/oozie-cli/{{ item.clidir }}/
      with_items: 
        - "{{ oozielist }}"
      tags:
        - CPLOCAL

    - name: Modify each job.properties file
      lineinfile:
        path: /home/lcia-dna/oozie-cli/{{ item.clidir }}/job.properties
        insertafter: 'oozie.use.system.libpath=True'
        line: 'oozie.wf.application.path=hdfs://lcia-digitaldna-bdp/user/hue/oozie/workspaces/{{ item.hdfsdir }}'
      with_items: 
        - "{{ oozielist }}"
      tags:
        - MODPROPERTI

