# -------------------------------------------------------------------------------------------
# Program : oozie_cli_prepare3.yml
# Purpose : oozie cli basic configuration setting  
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook oozie_cli_prepare3.yml -t MKDIR, CPLOCAL, MODPROPERTI
# -------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge02
  remote_user: admin
  become: yes
  become_user: lcia-dna
  become_method: sudo
  vars:
    oozielist:
      - {clidir: WFO_RE02_ANA_DD, hdfsdir: hue-oozie-1512975553.27}
      - {clidir: WFO_RE03_SOR_MM, hdfsdir: hue-oozie-1512973337.91}
      - {clidir: WFO_RE04_ANA_DD, hdfsdir: hue-oozie-1518155723.48}

  tasks:
    - name: "create directory for each oozie job cli"
      file:
        path: /home/lcia-dna/oozie-cli/{{ item.clidir }}
        state: directory 
        owner: lcia-dna
        group: hadoop
        mode: 0755
      with_items: 
        - "{{ oozielist }}"
      tags:
        - MKDIR

    - name: Copy file from HDFS to local 
      shell: >
        /usr/bin/hdfs dfs -copyToLocal 
        /user/hue/oozie/workspaces/{{ item.hdfsdir }}/job.properties 
        /home/lcia-dna/oozie-cli/{{ item.clidir }}/
      with_items: 
        - "{{ oozielist }}"
      tags:
        - CPLOCAL

    - name: Modify each job.properties file
      lineinfile:
        path: /home/lcia-dna/oozie-cli/{{ item.clidir }}/job.properties
        insertafter: 'oozie.use.system.libpath=True'
        line: 'oozie.wf.application.path=hdfs://lcia-digitaldna-bdp/user/hue/oozie/workspaces/{{ item.hdfsdir }}'
      with_items: 
        - "{{ oozielist }}"
      tags:
        - MODPROPERTI

