############################################################################################################
# 1. Program     : prod_reload_ider.yml
# 2. Description : when after dna product code change 
# 3. Creator     : Lee Sang Hyoung
# 4. Syntax      : 
#    Syntax1     : ansible-playbook prod_reload_ider.yml -t DNA -e '{"rlddate1_1":20160101,"rlddate1_2":20170630,"rlddate2_1":201301,"rlddate2_2":yyyymm(recently month),"rlddate3_1":20160101,"rlddate3_2":yyyymmdd(Recently day)}'
#    Syntax2     : ansible-playbook prod_reload_ider.yml -t DW
#    Syntax3     : ansible-playbook prod_reload_ider.yml -e '{"rlddate1_1":20160101,"rlddate1_2":20170630,"rlddate2_1":201301,"rlddate2_2":yyyymm(recently month),"rlddate3_1":20160101,"rlddate3_2":yyyymmdd(Recently day)}'
############################################################################################################
---
- hosts: lcia-etl01
  remote_user: admin
  become: true
  become_user: dsadm
  become_method: sudo
  vars:
    - project: "LCIA"
  tags:
    - DW
  tasks:
    ###############################################################
    # IDDZ_ANA_SAL20310_F : 월별닐슨판매분석 
    # IDDZ_ANA_SAL20110_F : 월별엘포인트Seg판매분석
    # IDDZ_ANA_SAL20210_F : 월볊엘포인트POS판매분석 
    ###############################################################
    - name: DataStage job run in asynchronously.
      vars:
        datastage_jobs:
          - "IDDZ_ANA_SAL20310_F"
          - "IDDZ_ANA_SAL20110_F"
          - "IDDZ_ANA_SAL20210_F"
        etljob: "{{ item }}"
      include_tasks: dsetl_work_ided.yml
      with_items:
        - "{{ datastage_jobs | batch(3) | list }}"

- hosts: lcia-dnaedge02
  remote_user: admin
  become: yes
  become_user: lcia-dna
  become_method: sudo
  vars: 
    ###############################################################
    # 엘포인트SEG 집계 초기 / 재적재 
    # 2016.01.01 ~ 2017.06.30 (현재 - 18.04 받은데이터)
    ###############################################################
    oozielist1: 
      - {jobname: WFO_RE02_ANA_DD, jobid: hue-oozie-1512975553.27} 

    ###############################################################
    # 닐슨POS 초기 / 재적재 
    # 2013.01부터 최근월(재적재월) 까지 
    ###############################################################
    oozielist2: 
      - {jobname: WFO_RE03_SOR_MM, jobid: hue-oozie-1512973337.91}

    ###############################################################
    # 엘포인트POS 집계 초기 / 재적재
    # 2016.01.01 ~ 최근 일(재적재일) 까지 
    ###############################################################
    oozielist3: 
      - {jobname: WFO_RE04_ANA_DD, jobid: hue-oozie-1518155723.48}

  tags:
    - DNA
 
  tasks:
    #################################
    # 엘포인트 SEG 집계 초기/재 적재
    #################################
    - template: 
        src: /etc/ansible/template/{{ jobname }}.j2
        dest: /home/lcia-dna/oozie-cli/{{ jobname }}/job.properties
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
        - reloaddate1: "{{ rlddate1_1 }}"
        - reloaddate2: "{{ rlddate1_2 }}"
      with_items: 
        - "{{ oozielist1 }}" 

    - name: job 1 oozie "{{ item.jobname }}"  
      include_tasks: prod_reload_ided.yml
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
      with_items: 
        - "{{ oozielist1 }}" 

    #################################
    # 닐슨POS집계 초기/재 적재
    #################################
    - template: 
        src: /etc/ansible/template/{{ jobname }}.j2
        dest: /home/lcia-dna/oozie-cli/{{ jobname }}/job.properties
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
        - reloaddate1: "{{ rlddate2_1 }}"
        - reloaddate2: "{{ rlddate2_2 }}"
      with_items: 
        - "{{ oozielist2 }}" 

    - name: job 2 oozie "{{ item.jobname }}"  
      include_tasks: prod_reload_ided.yml
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
      with_items: 
        - "{{ oozielist2 }}" 

    #################################
    # 엘포인트 POS 집계 초기/재 적재
    #################################
    - template: 
        src: /etc/ansible/template/{{ jobname }}.j2
        dest: /home/lcia-dna/oozie-cli/{{ jobname }}/job.properties
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
        - reloaddate1: "{{ rlddate3_1 }}"
        - reloaddate2: "{{ rlddate3_2 }}"
      with_items: 
        - "{{ oozielist3 }}" 

    - name: job 3 oozie "{{ item.jobname }}"  
      include_tasks: prod_reload_ided.yml
      vars: 
        - jobname: "{{ item.jobname }}" 
        - jobid: "{{ item.jobid }}"
      with_items: 
        - "{{ oozielist3 }}" 

