# -------------------------------------------------------------------------------------------
# Program : replace_work.yml
# Purpose : file contents change test 
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook replace_work.yml -t FILE
#           ansible-playbook replace_work.yml -t HDFS
# -------------------------------------------------------------------------------------------
---
- hosts: lcia-dnaedge02 
  remote_user: admin
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: lineinfile job 
      replace:
        path: /home/admin/work/{{ item.job }}
        regexp: '(?<=INSERT OVERWRITE TABLE )(.*)(?={{ item.table }} PARTITION)'
        replace: 'LCIA.'
      register: jobresult
      with_items:
        - { job: ANA_SAL10010_M.hql, table: ANA_SAL10010_M }
        - { job: ANA_SAL10011_M.hql, table: ANA_SAL10011_M }
        - { job: ANA_SAL10040_M.hql, table: ANA_SAL10040_M }
        - { job: ANA_SAL10041_M.hql, table: ANA_SAL10041_M }
        - { job: ANA_SAL10042_M.hql, table: ANA_SAL10042_M }
        - { job: ANA_SAL10030_M.hql, table: ANA_SAL10030_M }
        - { job: ANA_SAL10031_M.hql, table: ANA_SAL10031_M }
        - { job: ANA_SAL10032_M.hql, table: ANA_SAL10032_M }
        - { job: ANA_SAL10033_M.hql, table: ANA_SAL10033_M }
        - { job: ANA_SAL10034_M.hql, table: ANA_SAL10034_M }
#       - { job: test.hql, table: ANA_SAL10033_M }
      tags: FILE

    - name: Print Job Result
      debug:
        msg: "Job Result: {{ jobresult }}"
      tags: FILE
  
    - name: "file copy & rename"
      copy:
        src: /home/admin/work/{{ item.job }}
        dest: /home/lcia-dna/work/oozie_work/PADEV_{{item.job}}
        owner: lcia-dna
        group: hadoop
        remote_src: yes
      with_items:
        - { job: ANA_SAL10010_M.hql }
        - { job: ANA_SAL10011_M.hql }
        - { job: ANA_SAL10040_M.hql }
        - { job: ANA_SAL10041_M.hql }
        - { job: ANA_SAL10042_M.hql }
        - { job: ANA_SAL10030_M.hql }
        - { job: ANA_SAL10031_M.hql }
        - { job: ANA_SAL10032_M.hql }
        - { job: ANA_SAL10033_M.hql }
        - { job: ANA_SAL10034_M.hql }
#       - { job: test.hql }
      tags: FILE

    - name: Copy file to HDFS
      remote_user: admin
      become: true
      become_user: lcia-dna
      become_method: sudo
      command: /usr/bin/hdfs dfs -copyFromLocal -f /home/lcia-dna/work/oozie_work/{{ item.job }} /LCIA/workFlowHiveScript
      register: jobresult
      with_items: 
        - { job: PADEV_ANA_SAL10010_M.hql }
        - { job: PADEV_ANA_SAL10011_M.hql }
        - { job: PADEV_ANA_SAL10040_M.hql }
        - { job: PADEV_ANA_SAL10041_M.hql }
        - { job: PADEV_ANA_SAL10042_M.hql }
        - { job: PADEV_ANA_SAL10030_M.hql }
        - { job: PADEV_ANA_SAL10031_M.hql }
        - { job: PADEV_ANA_SAL10032_M.hql }
        - { job: PADEV_ANA_SAL10033_M.hql }
        - { job: PADEV_ANA_SAL10034_M.hql }
#       - { job: PADEV_test.hql }
      tags: HDFS

    - name: Print Job Result 2
      debug:
        msg: "Job Result: {{ jobresult }}"
      tags: HDFS

