###########################################################################################
# Program     : sudoer_work.yml
# Description : allow sudo feature 
# Creator     : Lee Sang Hyoung
# Syntax      : ansible-playbook sudoer_work.yml -e "host=wexnode user=admin" --ask-pass
###########################################################################################
--- 
- hosts: "{{ host }}"
  user: root

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user: name="{{ user }}" groups=wheel append=yes state=present createhome=yes

