# #########################################################################################
# Program : cognos_was_restart.yml
# Creator : Lee Sang Hyoung
# Syntax : ansible-playbook test2.yml
# #########################################################################################
---
- hosts: lcia-dnawex01
  become: true
  remote_user: admin
  become_user: esadmin
  become_method: sudo

  tasks:
    - name: wex01접속 테스트
      shell: date
      register: rslt
      ignore_errors: yes

    - debug: 
        msg: 
          - "상태 : {{ rslt.stdout }}"
          

