##########################################################################################
# Program : wex_service_start
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook wex_service_start.yml
#           ansible-playbook wex_service_start.yml -t VMON
#           ansible-playbook wex_service_start.yml -t VMON,WEX
#           ansible-playbook wex_service_start.yml -t WEX,DNA,DW
##########################################################################################
---
#############################################################
# 작업내용 : WEX VM 시작
# Woking Server : WEX 01,02,03,04번
#############################################################
- hosts: localhost
  tags:
    - VMON

  tasks:
    ############################################################
    # WEX VM 시작
    ############################################################
    - name: "▶ 1. WEX VM Start REST API CALL "
      uri:
        url: https://10.210.31.10:9440/api/nutanix/v2.0/vms/{{ item.vmuuid }}/set_power_state/
        method: POST
        user: admin
        password: Nutanix/4u!
        body: '{"transition": "ON", "uuid": "{{ item.vmuuid }}"}'
        validate_certs: no
        body_format: json
        force_basic_auth: yes
        status_code: 201
      register: job_result
      ignore_errors: yes
      with_items:
        - { vmuuid: 738a529c-31af-44a1-bf2a-5ca104b42c2e }


    - name: "▶ 1. WEX VM Start REST API CALL 결과"
      debug:
        msg:
          - "{{ job_result }}"
#         - "Ѱ {{ lookup('pipe','date +%Y-%m-%d/%H:%M:%S') }}"

#############################################################
# 작업내용 : WEX VM 시작 후 SSH연결 상태 확인 
# Woking Server : WEX 01,02,03,04번
# lcia-dnawex01,lcia-dnawex02,lcia-dnawex03,lcia-dnawex04
#############################################################
- hosts: lcia-dnawex04
  gather_facts: no
  tags:
    - VMON

  tasks:
    ############################################################
    # WEX VM Wait for system to become reachable
    ############################################################
    - name: "▶ 2. Wait 600 seconds, but only start checking after 100 seconds"
      wait_for_connection:
        delay: 50
        timeout: 150

    - name: VM Gather facts for first time
      setup:
      register: job_result

    - name: "▶ 2. WEX VM Start 후 접속상태"
      debug:
        msg:
          - "{{ job_result.ansible_facts.ansible_fqdn }}"
          - "{{ job_result.ansible_facts.ansible_hostname }}"
          - "{{ job_result.ansible_facts.ansible_env.SSH_CONNECTION }}"
          - "Ѱ {{ lookup('pipe','date +%Y-%m-%d/%H:%M:%S') }}"

#########################################################################
#        - { vmuuid: d7169f77-262b-4b96-a9e7-8837ecc7a4e3 }
#        - { vmuuid: 5ad7d04f-10cc-4826-8412-7c79ac46d8e2 }
#        - { vmuuid: 620a071c-50a1-41d8-b9a2-32664cff2032 }
