---
- hosts: scansrc
  #remote_user: admin

  tasks:
    - name: Work. file Copy from window machine to ansible zone 
      #command: scp /lcia/data/test.csv admin@10.109.2.71:/lcia/src/DW/
      fetch: 
        src: C:/test/test.xlsx
        dest: /lcia/data/test.xlsx flat=yes

  #tasks:
  # - name: Work 2. file Copy to landing zone
  #   copy:
  #     src: "{{ item }}"
  #     dest: /lcia/src/DW/
  #   with_fileglob:
  #     - /lcia/data/*.csv
