---

- hosts: localhost
  remote_user: admin

  tasks:

  - name: simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
    command: /bin/sleep 10
    async: 45
    poll: 0
    register: yum_sleeper

  - name: 'check on fire and forget task'
    async_status: jid={{ yum_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 30

  - name: 'What happens after async module call' 
    shell: echo 'What happens? Is it OK?'
