---
- hosts: testnode:landnode
  gather_facts: no
  strategy: free
  tasks:
    - include_tasks: devnode_test.yml
      when: "'testnode' in group_names"

    - include_tasks: landnode_test.yml
      when: "'landnode' in group_names"

