---
- hosts: testnode:landnode
  gather_facts: no
  strategy: free
  tasks:
    - include_tasks: test_devnode.yml
      when:  "'testnode' in group_names"
    - include_tasks: test_landnode.yml
      when: "'landnode' in group_names"
