#####################################################################################
# Program : aws_instance_test.yml
# Creator : Lee Sang Hyoung
# Syntax  : ansible-playbook aws_instance_test.yml
#####################################################################################
---
# Start a few existing instances, run some tasks
# and stop the instances
- name: Start Instances
  hosts: localhost
  gather_facts: false
  connection: local
   
  tasks:

    - name: Set fact with EC2 IP address
      set_fact:
        ec2_ip: "9.9.9.9"

    - name: Display the EC2 IP address
      debug:
        var: ec2_ip     

    - name: Add EC2 instance to inventory
      add_host:
        name: ec2_instance
        ansible_host: "{{ ec2_ip }}"
        ansible_user: centos  # Adjust the user as per your EC2 instance configuration
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      when: ec2_ip is defined

    - name: Set fact with EC2 instance name
      set_fact:
        ec2_instance: "ec2_instance"
      when: ec2_ip is defined

    - name: Print Hostname and IP Address
      debug:
        msg: "Hostname: {{ ec2_instance }} IP Address: {{ hostvars[ec2_instance].ansible_host }}"

