---
- name: Connect to Windows node
  hosts: windows
  gather_facts: no
  tasks:
     
    - name: run a cmd command
      win_command: cmd.exe /c mkdir C:\Temp\temp

    - name: run a vbs script
      win_command: cscript.exe script.vbs

    - name: run from specific folder, skip when condition already met
      win_command: wbadmin -backupTarget:C:\backup\
      args:
        chdir: C:\wdata\
        creates: C:\tbackup\
        
      
