---
- hosts: lcia-dnawex01
  remote_user: admin
  become: yes
  become_user: esadmin
  become_method: sudo

  tasks:
    - name: Start WEX Cralwer
      shell: cat /home/esadmin/ansible_wex/wex_session.dat
      register: crawler_session

    - name: "WEX 크롤링"
      include_tasks: test_included.yml
      vars:
        - sessionid: "{{ item }}"
      with_items:
        - "{{ crawler_session.stdout_lines }}"


